#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : desktop-icons
Version  : 20.04.0
Release  : 13
URL      : https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/archive/20.04.0/desktop-icons-20.04.0.tar.gz
Source0  : https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/archive/20.04.0/desktop-icons-20.04.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: desktop-icons-data = %{version}-%{release}
Requires: desktop-icons-license = %{version}-%{release}
Requires: desktop-icons-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson

%description
# Desktop Icons
## What  is it
A GNOME Shell extension for providing desktop icons.

%package data
Summary: data components for the desktop-icons package.
Group: Data

%description data
data components for the desktop-icons package.


%package license
Summary: license components for the desktop-icons package.
Group: Default

%description license
license components for the desktop-icons package.


%package locales
Summary: locales components for the desktop-icons package.
Group: Default

%description locales
locales components for the desktop-icons package.


%prep
%setup -q -n desktop-icons-20.04.0
cd %{_builddir}/desktop-icons-20.04.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586196649
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/desktop-icons
cp %{_builddir}/desktop-icons-20.04.0/LICENSE %{buildroot}/usr/share/package-licenses/desktop-icons/3449a0143409acce51896257065a03361e612271
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang desktop-icons

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.desktop-icons.gschema.xml
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/createFolderDialog.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/createThumbnail.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/dbusUtils.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopIconsUtil.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopManager.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/extension.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/fileItem.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/metadata.json
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/prefs.js
/usr/share/gnome-shell/extensions/desktop-icons@csoriano/stylesheet.css

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/desktop-icons/3449a0143409acce51896257065a03361e612271

%files locales -f desktop-icons.lang
%defattr(-,root,root,-)

